# CMake generated Testfile for 
# Source directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag
# Build directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(simdag-availability "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/availability/sd_availability.tesh")
set_tests_properties(simdag-availability PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
add_test(simdag-daxload "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/daxload/sd_daxload.tesh")
set_tests_properties(simdag-daxload PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
add_test(simdag-fail "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/fail/sd_fail.tesh")
set_tests_properties(simdag-fail PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
add_test(simdag-typed_tasks "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/typed_tasks/sd_typed_tasks.tesh")
set_tests_properties(simdag-typed_tasks PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
add_test(simdag-properties "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/properties/sd_properties.tesh")
set_tests_properties(simdag-properties PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
add_test(simdag-throttling "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/throttling/sd_throttling.tesh")
set_tests_properties(simdag-throttling PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
add_test(simdag-scheduling "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/scheduling/sd_scheduling.tesh")
set_tests_properties(simdag-scheduling PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
add_test(simdag-test "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/test/sd_test.tesh")
set_tests_properties(simdag-test PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;44;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/simdag/CMakeLists.txt;0;")
