# CMake generated Testfile for 
# Source directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/simdag
# Build directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/simdag
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(simdag-availability "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/availability/sd_availability.tesh")
add_test(simdag-daxload "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/daxload/sd_daxload.tesh")
add_test(simdag-fail "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/fail/sd_fail.tesh")
add_test(simdag-typed_tasks "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/typed_tasks/sd_typed_tasks.tesh")
add_test(simdag-properties "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/properties/sd_properties.tesh")
add_test(simdag-throttling "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/throttling/sd_throttling.tesh")
add_test(simdag-scheduling "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/scheduling/sd_scheduling.tesh")
add_test(simdag-test "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag" "/home/kien/project/fpga_network/SimGrid-3.21/examples/simdag/test/sd_test.tesh")
