# CMake generated Testfile for 
# Source directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag
# Build directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(simdag-availability "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/availability/sd_availability.tesh")
ADD_TEST(simdag-daxload "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/daxload/sd_daxload.tesh")
ADD_TEST(simdag-fail "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/fail/sd_fail.tesh")
ADD_TEST(simdag-typed_tasks "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/typed_tasks/sd_typed_tasks.tesh")
ADD_TEST(simdag-properties "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/properties/sd_properties.tesh")
ADD_TEST(simdag-throttling "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/throttling/sd_throttling.tesh")
ADD_TEST(simdag-scheduling "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/scheduling/sd_scheduling.tesh")
ADD_TEST(simdag-test "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/simdag/test/sd_test.tesh")
