# CMake generated Testfile for 
# Source directory: /home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt
# Build directory: /home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-xbt-cmdline "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/cmdline" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/cmdline" "cmdline.tesh")
set_tests_properties(tesh-xbt-cmdline PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;33;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-log_large "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/log_large" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/log_large" "log_large.tesh")
set_tests_properties(tesh-xbt-log_large PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;33;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-parallel_log_crashtest "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/parallel_log_crashtest" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/parallel_log_crashtest" "parallel_log_crashtest.tesh")
set_tests_properties(tesh-xbt-parallel_log_crashtest PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;33;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-parmap_test "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/parmap_test" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/parmap_test" "parmap_test.tesh")
set_tests_properties(tesh-xbt-parmap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;33;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-log "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/log_usage" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/log_usage/log_usage.tesh")
set_tests_properties(tesh-xbt-log PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;37;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/xbt/CMakeLists.txt;0;")
