# CMake generated Testfile for 
# Source directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy
# Build directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi-replay-multiple-manual-nojob "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_nojob.tesh")
set_tests_properties(smpi-replay-multiple-manual-nojob PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-empty1 "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_empty1.tesh")
set_tests_properties(smpi-replay-multiple-manual-empty1 PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-empty2 "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_empty2.tesh")
set_tests_properties(smpi-replay-multiple-manual-empty2 PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-mixed1 "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed1.tesh")
set_tests_properties(smpi-replay-multiple-manual-mixed1 PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-mixed2 "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2.tesh")
set_tests_properties(smpi-replay-multiple-manual-mixed2 PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-mixed2-st "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st.tesh")
set_tests_properties(smpi-replay-multiple-manual-mixed2-st PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-mixed2-st-noise "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_noise.tesh")
set_tests_properties(smpi-replay-multiple-manual-mixed2-st-noise PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-mixed2-st-sr "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_sr.tesh")
set_tests_properties(smpi-replay-multiple-manual-mixed2-st-sr PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
add_test(smpi-replay-multiple-manual-mixed2-st-sr-noise "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_sr_noise.tesh")
set_tests_properties(smpi-replay-multiple-manual-mixed2-st-sr-noise PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;21;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/CMakeLists.txt;0;")
