# CMake generated Testfile for 
# Source directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy
# Build directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi-replay-multiple-manual-nojob "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_nojob.tesh")
add_test(smpi-replay-multiple-manual-empty1 "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_empty1.tesh")
add_test(smpi-replay-multiple-manual-empty2 "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_empty2.tesh")
add_test(smpi-replay-multiple-manual-mixed1 "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed1.tesh")
add_test(smpi-replay-multiple-manual-mixed2 "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2.tesh")
add_test(smpi-replay-multiple-manual-mixed2-st "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st.tesh")
add_test(smpi-replay-multiple-manual-mixed2-st-noise "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_noise.tesh")
add_test(smpi-replay-multiple-manual-mixed2-st-sr "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_sr.tesh")
add_test(smpi-replay-multiple-manual-mixed2-st-sr-noise "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_sr_noise.tesh")
