# CMake generated Testfile for 
# Source directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy
# Build directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(smpi-replay-multiple-manual-nojob "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_nojob.tesh")
ADD_TEST(smpi-replay-multiple-manual-empty1 "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_empty1.tesh")
ADD_TEST(smpi-replay-multiple-manual-empty2 "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_empty2.tesh")
ADD_TEST(smpi-replay-multiple-manual-mixed1 "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed1.tesh")
ADD_TEST(smpi-replay-multiple-manual-mixed2 "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2.tesh")
ADD_TEST(smpi-replay-multiple-manual-mixed2-st "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st.tesh")
ADD_TEST(smpi-replay-multiple-manual-mixed2-st-noise "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_noise.tesh")
ADD_TEST(smpi-replay-multiple-manual-mixed2-st-sr "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_sr.tesh")
ADD_TEST(smpi-replay-multiple-manual-mixed2-st-sr-noise "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual_mixed2_st_sr_noise.tesh")
