# CMake generated Testfile for 
# Source directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90
# Build directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi-energy-f90-thread "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/energy.tesh")
set_tests_properties(smpi-energy-f90-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;5;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;0;")
add_test(smpi-energy-f90-ucontext "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/energy.tesh")
set_tests_properties(smpi-energy-f90-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;5;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;0;")
add_test(smpi-energy-f90-raw "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/energy.tesh")
set_tests_properties(smpi-energy-f90-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;5;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;0;")
add_test(smpi-energy-f90-boost "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/energy.tesh")
set_tests_properties(smpi-energy-f90-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;5;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/f90/CMakeLists.txt;0;")
