# CMake generated Testfile for 
# Source directory: /home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh
# Build directory: /home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-self-setenv "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/setenv.tesh")
add_test(tesh-self-set-output-ignore "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/set-output-ignore.tesh")
add_test(tesh-self-set-output-sort "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/set-output-sort.tesh")
add_test(tesh-self-set-return "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/set-return.tesh")
add_test(tesh-self-set-timeout "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/set-timeout.tesh")
add_test(tesh-self-background "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/background.tesh")
add_test(tesh-self-basic "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/basic.tesh")
add_test(tesh-self-bg-basic "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/bg-basic.tesh")
add_test(tesh-self-bg-set-signal "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/bg-set-signal.tesh")
add_test(tesh-self-catch-return "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/catch-return.tesh")
add_test(tesh-self-catch-signal "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/catch-signal.tesh")
add_test(tesh-self-catch-timeout "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/catch-timeout.tesh")
add_test(tesh-self-catch-wrong-output "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/catch-wrong-output.tesh")
add_test(tesh-self-cd "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/cd.tesh")
add_test(tesh-self-color "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/color.tesh")
add_test(tesh-self-ignore-regexp "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/ignore-regexp.tesh")
add_test(tesh-self-IO-bigsize "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/IO-bigsize.tesh")
add_test(tesh-self-IO-broken-pipe "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/IO-broken-pipe.tesh")
add_test(tesh-self-IO-orders "/usr/bin/python3" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/bin" "/home/kien/project/ipdps2022/fpga_network/SimGrid-3.21/tools/tesh/IO-orders.tesh")
