# CMake generated Testfile for 
# Source directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi
# Build directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(smpi-tracing "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace/trace.tesh")
ADD_TEST(smpi-tracing-simple "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace_simple/trace_simple.tesh")
ADD_TEST(smpi-tracing-call-location "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location/trace_call_location.tesh")
ADD_TEST(smpi-replay "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/replay/replay.tesh")
ADD_TEST(smpi-energy-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/bin" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
ADD_TEST(smpi-energy-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/bin" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
ADD_TEST(smpi-energy-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/bin" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
ADD_TEST(smpi-energy-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/bin" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
ADD_TEST(smpi-ampi "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/ampi/ampi.tesh")
