# CMake generated Testfile for 
# Source directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/smpi
# Build directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/smpi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi-tracing "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace/trace.tesh")
add_test(smpi-tracing-simple "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple/trace_simple.tesh")
add_test(smpi-tracing-call-location "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location/trace_call_location.tesh")
add_test(smpi-replay "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/replay/replay.tesh")
add_test(smpi-energy-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
add_test(smpi-energy-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
add_test(smpi-energy-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
add_test(smpi-energy-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
add_test(smpi-ampi "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/ampi/ampi.tesh")
