# CMake generated Testfile for 
# Source directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi
# Build directory: /home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi-tracing "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace/trace.tesh")
set_tests_properties(smpi-tracing PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;73;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-tracing-simple "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace_simple/trace_simple.tesh")
set_tests_properties(smpi-tracing-simple PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;74;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-tracing-call-location "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/trace_call_location/trace_call_location.tesh")
set_tests_properties(smpi-tracing-call-location PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;75;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-replay "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/replay/replay.tesh")
set_tests_properties(smpi-replay PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;76;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-thread "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;77;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-ucontext "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;77;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-raw "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;77;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-boost "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/bin" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;77;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-ampi "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi" "--setenv" "platfdir=/home/kienpham/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi" "/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/ampi/ampi.tesh")
set_tests_properties(smpi-ampi PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;79;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/examples/smpi/CMakeLists.txt;0;")
