# CMake generated Testfile for 
# Source directory: /home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u
# Build directory: /home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-s4u-actor-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
add_test(tesh-s4u-actor-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
add_test(tesh-s4u-actor-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
add_test(tesh-s4u-actor-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
add_test(tesh-s4u-actor-autorestart-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
add_test(tesh-s4u-actor-autorestart-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
add_test(tesh-s4u-actor-autorestart-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
add_test(tesh-s4u-actor-autorestart-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
add_test(tesh-s4u-actor-migration-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
add_test(tesh-s4u-actor-migration-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
add_test(tesh-s4u-actor-migration-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
add_test(tesh-s4u-actor-migration-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
add_test(tesh-s4u-activity-lifecycle-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
add_test(tesh-s4u-activity-lifecycle-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
add_test(tesh-s4u-activity-lifecycle-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
add_test(tesh-s4u-activity-lifecycle-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
add_test(tesh-s4u-cloud-interrupt-migration-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
add_test(tesh-s4u-cloud-interrupt-migration-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
add_test(tesh-s4u-cloud-interrupt-migration-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
add_test(tesh-s4u-cloud-interrupt-migration-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
add_test(tesh-s4u-concurrent_rw-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
add_test(tesh-s4u-concurrent_rw-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
add_test(tesh-s4u-concurrent_rw-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
add_test(tesh-s4u-concurrent_rw-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
add_test(tesh-s4u-listen_async "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/listen_async" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/listen_async" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/listen_async/listen_async.tesh")
add_test(tesh-s4u-pid "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/pid" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/pid" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/pid/pid.tesh")
add_test(tesh-s4u-storage_client_server "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/storage_client_server" "--setenv" "platfdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/storage_client_server" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/storage_client_server/storage_client_server.tesh")
add_test(tesh-s4u-comm-pt2pt "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/s4u/comm-pt2pt/comm-pt2pt" "/home/kien/project/fpga_network/SimGrid-3.21/examples/platforms/cluster_backbone.xml")
