# CMake generated Testfile for 
# Source directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u
# Build directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(tesh-s4u-actor-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
ADD_TEST(tesh-s4u-actor-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
ADD_TEST(tesh-s4u-actor-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
ADD_TEST(tesh-s4u-actor-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor/actor.tesh")
ADD_TEST(tesh-s4u-actor-autorestart-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
ADD_TEST(tesh-s4u-actor-autorestart-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
ADD_TEST(tesh-s4u-actor-autorestart-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
ADD_TEST(tesh-s4u-actor-autorestart-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-autorestart/actor-autorestart.tesh")
ADD_TEST(tesh-s4u-actor-migration-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
ADD_TEST(tesh-s4u-actor-migration-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
ADD_TEST(tesh-s4u-actor-migration-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
ADD_TEST(tesh-s4u-actor-migration-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/actor-migration/actor-migration.tesh")
ADD_TEST(tesh-s4u-activity-lifecycle-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
ADD_TEST(tesh-s4u-activity-lifecycle-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
ADD_TEST(tesh-s4u-activity-lifecycle-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
ADD_TEST(tesh-s4u-activity-lifecycle-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/activity-lifecycle/activity-lifecycle.tesh")
ADD_TEST(tesh-s4u-cloud-interrupt-migration-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
ADD_TEST(tesh-s4u-cloud-interrupt-migration-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
ADD_TEST(tesh-s4u-cloud-interrupt-migration-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
ADD_TEST(tesh-s4u-cloud-interrupt-migration-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/cloud-interrupt-migration/cloud-interrupt-migration.tesh")
ADD_TEST(tesh-s4u-concurrent_rw-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
ADD_TEST(tesh-s4u-concurrent_rw-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
ADD_TEST(tesh-s4u-concurrent_rw-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
ADD_TEST(tesh-s4u-concurrent_rw-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/concurrent_rw/concurrent_rw.tesh")
ADD_TEST(tesh-s4u-listen_async "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/listen_async" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/listen_async" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/listen_async/listen_async.tesh")
ADD_TEST(tesh-s4u-pid "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/pid" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/pid" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/pid/pid.tesh")
ADD_TEST(tesh-s4u-storage_client_server "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/storage_client_server" "--setenv" "platfdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/storage_client_server" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/storage_client_server/storage_client_server.tesh")
ADD_TEST(tesh-s4u-comm-pt2pt "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/s4u/comm-pt2pt/comm-pt2pt" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/platforms/cluster_backbone.xml")
