# CMake generated Testfile for 
# Source directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave
# Build directory: /home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi-msg-masterslave-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
add_test(smpi-msg-masterslave-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
add_test(smpi-msg-masterslave-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
add_test(smpi-msg-masterslave-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/kien/project/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
