# CMake generated Testfile for 
# Source directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave
# Build directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(smpi-msg-masterslave-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
ADD_TEST(smpi-msg-masterslave-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
ADD_TEST(smpi-msg-masterslave-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
ADD_TEST(smpi-msg-masterslave-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave" "/home/aaa10078nj/fpga_network/SimGrid-3.21/examples/smpi/smpi_msg_masterslave/msg_smpi.tesh")
