# CMake generated Testfile for 
# Source directory: /home/aaa10078nj/fpga_network/SimGrid-3.21
# Build directory: /home/aaa10078nj/fpga_network/SimGrid-3.21
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(testall "/home/aaa10078nj/fpga_network/SimGrid-3.21/testall")
SUBDIRS(examples/java)
SUBDIRS(examples/msg)
SUBDIRS(examples/msg/mc)
SUBDIRS(examples/s4u)
SUBDIRS(examples/simdag)
SUBDIRS(examples/smpi)
SUBDIRS(examples/smpi/NAS)
SUBDIRS(examples/smpi/smpi_msg_masterslave)
SUBDIRS(examples/smpi/replay_multiple)
SUBDIRS(examples/smpi/replay_multiple_manual_deploy)
SUBDIRS(examples/smpi/load_balancer_replay)
SUBDIRS(examples/smpi/energy/f77)
SUBDIRS(examples/smpi/energy/f90)
SUBDIRS(teshsuite/java)
SUBDIRS(teshsuite/mc)
SUBDIRS(teshsuite/msg)
SUBDIRS(teshsuite/s4u)
SUBDIRS(teshsuite/simdag)
SUBDIRS(teshsuite/simix)
SUBDIRS(teshsuite/smpi)
SUBDIRS(teshsuite/surf)
SUBDIRS(teshsuite/xbt)
SUBDIRS(teshsuite/smpi/isp/umpire)
SUBDIRS(teshsuite/smpi/mpich3-test)
SUBDIRS(teshsuite/smpi/mpich3-test/attr)
SUBDIRS(teshsuite/smpi/mpich3-test/coll)
SUBDIRS(teshsuite/smpi/mpich3-test/comm)
SUBDIRS(teshsuite/smpi/mpich3-test/datatype)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/attr)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/coll)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/info)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/comm)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/datatype)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/ext)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/init)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/pt2pt)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/util)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/topo)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/rma)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/coll)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/datatype)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/info)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/init)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/pt2pt)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/util)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/rma)
SUBDIRS(teshsuite/smpi/mpich3-test/group)
SUBDIRS(teshsuite/smpi/mpich3-test/info)
SUBDIRS(teshsuite/smpi/mpich3-test/init)
SUBDIRS(teshsuite/smpi/mpich3-test/pt2pt)
SUBDIRS(teshsuite/smpi/mpich3-test/topo)
SUBDIRS(teshsuite/smpi/mpich3-test/rma)
SUBDIRS(teshsuite/smpi/mpich3-test/perf)
SUBDIRS(tools)
SUBDIRS(tools/graphicator)
SUBDIRS(tools/tesh)
