# CMake generated Testfile for 
# Source directory: /home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix
# Build directory: /home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-simix-factory-default "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_raw.tesh")
set_tests_properties(tesh-simix-factory-default PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;19;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(stack-overflow-thread "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
set_tests_properties(stack-overflow-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;29;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(stack-overflow-ucontext "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
set_tests_properties(stack-overflow-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;29;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(stack-overflow-raw "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
set_tests_properties(stack-overflow-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;29;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(stack-overflow-boost "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
set_tests_properties(stack-overflow-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;29;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(generic-simcalls-thread "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
set_tests_properties(generic-simcalls-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;32;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(generic-simcalls-ucontext "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
set_tests_properties(generic-simcalls-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;32;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(generic-simcalls-raw "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
set_tests_properties(generic-simcalls-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;32;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(generic-simcalls-boost "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kienpham/project/fpga_network/SimGrid-3.21" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
set_tests_properties(generic-simcalls-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;64;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;32;ADD_TESH_FACTORIES;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(tesh-simix-factory-raw "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_raw.tesh")
set_tests_properties(tesh-simix-factory-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;41;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(tesh-simix-factory-thread "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_thread.tesh")
set_tests_properties(tesh-simix-factory-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;41;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(tesh-simix-factory-boost "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_boost.tesh")
set_tests_properties(tesh-simix-factory-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;41;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
add_test(tesh-simix-factory-ucontext "/usr/bin/python3" "/home/kienpham/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_ucontext.tesh")
set_tests_properties(tesh-simix-factory-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/kienpham/project/fpga_network/SimGrid-3.21/tools/cmake/Tests.cmake;49;ADD_TEST;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;41;ADD_TESH;/home/kienpham/project/fpga_network/SimGrid-3.21/teshsuite/simix/CMakeLists.txt;0;")
