# CMake generated Testfile for 
# Source directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix
# Build directory: /home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(tesh-simix-factory-default "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_raw.tesh")
ADD_TEST(stack-overflow-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
ADD_TEST(stack-overflow-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
ADD_TEST(stack-overflow-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
ADD_TEST(stack-overflow-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
ADD_TEST(generic-simcalls-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
ADD_TEST(generic-simcalls-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
ADD_TEST(generic-simcalls-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
ADD_TEST(generic-simcalls-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/aaa10078nj/fpga_network/SimGrid-3.21" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
ADD_TEST(tesh-simix-factory-raw "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_raw.tesh")
ADD_TEST(tesh-simix-factory-thread "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_thread.tesh")
ADD_TEST(tesh-simix-factory-boost "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_boost.tesh")
ADD_TEST(tesh-simix-factory-ucontext "/home/aaa10078nj/.local/bin/python3" "/home/aaa10078nj/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/aaa10078nj/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_ucontext.tesh")
