# CMake generated Testfile for 
# Source directory: /home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix
# Build directory: /home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-simix-factory-default "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_raw.tesh")
add_test(stack-overflow-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
add_test(stack-overflow-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
add_test(stack-overflow-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
add_test(stack-overflow-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/stack-overflow" "stack-overflow.tesh")
add_test(generic-simcalls-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
add_test(generic-simcalls-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
add_test(generic-simcalls-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
add_test(generic-simcalls-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "--setenv" "srcdir=/home/kien/project/fpga_network/SimGrid-3.21" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/generic-simcalls" "generic-simcalls.tesh")
add_test(tesh-simix-factory-raw "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_raw.tesh")
add_test(tesh-simix-factory-thread "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_thread.tesh")
add_test(tesh-simix-factory-boost "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_boost.tesh")
add_test(tesh-simix-factory-ucontext "/usr/bin/python3" "/home/kien/project/fpga_network/SimGrid-3.21/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "--cd" "/home/kien/project/fpga_network/SimGrid-3.21/teshsuite/simix/check-defaults" "factory_ucontext.tesh")
